rpc: http://localhost:8114

# sUDT script definition
udt:
  deps:
    -
      txHash: 0xc1b2ae129fad7465aaa9acc9785f842ba3e6e8b8051d899defa89f5508a77958
      index: 0
      depType: code
  script:
    codeHash: 0x48dbf59b4c7ee1547238021b4869bceedf4eea6b43772e5d66ef8865b6ae7212
    hashType: data

# Anyone can pay script definition
acp:
  deps:
    -
      txHash: 0x4f32b3e39bd1b6350d326fdfafdfe05e5221865c3098ae323096f0bfc69e0a8c
      index: 0
      depType: dep_group
  script:
    codeHash: 0x86a1c6987a4acbe1a887cca4c9dd2ac9fcb07405bbeda51b861b18bbf7492c4b
    hashType: type
